"""Stitch the six per-task THUNDER seed-spread panels (written by
waiv/scripts/seed_spread_tables.py as tables/seed_thunder_{knn,lp,fewshot,seg,ece,adv}.tex)
into the two per-dataset blocks of the appendix's single THUNDER table (parts one and two):

  tables/thunder_per_ds_cls.tex    k-NN, linear-probe and 16-shot macro-F1
  tables/thunder_per_ds_other.tex  segmentation F1, linear-probe ECE, adversarial F1 drop

(Formerly written as tables/seed_thunder_{cls,other}.tex, now retired to tables/unused/.)

Cells are copied verbatim (base -> tuned +/- 2 SD, bold when the change clears 2 SD);
the panels' Mean rows are dropped, since the task means are already the top block of the table.
The six panel files are retired to tables/unused/; this script reads them from
tables/ if present, else from tables/unused/.

    python3 paper/scripts/combine_seed_thunder.py   (reads/writes $SPECTRA_PAPER/tables)
"""
import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "scripts"))
from _config import PAPER_TABLES  # noqa: E402

HEADER = "% Generated by scripts/combine_seed_thunder.py from seed_thunder_*.tex -- do not hand-edit.\n"
GROUPS = {
    "cls": [("knn", "$k$-NN macro-F1\\,$\\uparrow$"),
            ("lp", "Linear-probe macro-F1\\,$\\uparrow$"),
            ("fewshot", "16-shot macro-F1\\,$\\uparrow$")],
    "other": [("seg", "Segmentation F1\\,$\\uparrow$"),
              ("ece", "Linear-probe ECE\\,$\\downarrow$"),
              ("adv", "Adversarial macro-F1 drop\\,$\\downarrow$ (fp32-attack cells)")],
}


def panel(stem):
    for d in (PAPER_TABLES, PAPER_TABLES / "unused"):
        p = f"{d}/seed_thunder_{stem}.tex"
        if os.path.exists(p):
            lines = open(p).read().splitlines()
            break
    else:
        raise FileNotFoundError(stem)
    begin = next(l for l in lines if l.startswith("\\begin{tabular}"))
    head = next(l for l in lines if l.startswith("Dataset &"))
    body = [l for l in lines if l.endswith("\\\\") and not l.startswith("Dataset &")]
    return begin, head, body


for name, stems in GROUPS.items():
    out = []
    for i, (stem, title) in enumerate(stems):
        begin, head, body = panel(stem)
        ncol = head.count("&") + 1
        if i == 0:
            out += [HEADER + begin, "\\toprule", head, "\\midrule"]
        else:
            out.append("\\midrule")
        out.append(f"\\multicolumn{{{ncol}}}{{l}}{{\\emph{{{title}}}}} \\\\")
        out.append("\\addlinespace[1pt]")
        for l in body:
            if l.startswith("Mean"):
                # Task means live only in the top block of the appendix table
                # (tables/thunder_ranks_full.tex); the per-dataset blocks carry per-dataset rows only.
                continue
            out.append(l)
    out += ["\\bottomrule", "\\end{tabular}"]
    open(PAPER_TABLES / f"thunder_per_ds_{name}.tex", "w").write("\n".join(out) + "\n")
    print(f"wrote {PAPER_TABLES}/thunder_per_ds_{name}.tex ({sum(1 for l in out if l.endswith(chr(92)*2))} rows)")
