"""tables/hest_per_task.tex -- ONE HEST table: per-task Pearson r (+/- two sample SDs over
the adapter seeds) and its rank in the same cell.  Value line and SD from waiv
docs/hest_per_task.md (which lists mean +/- one sample SD); rank line and trailing columns
from tables/hest_ranks.tex (which stays the upstream-generated source of ranks).
This table absorbed the former tables/seed_hest.tex (per-task mean +/- 2 SD), so the
across-seed spread appears here once."""
import re
import sys
from pathlib import Path
REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "scripts"))
from _config import PAPER_TABLES  # noqa: E402
MD=str(REPO / "docs/hest_per_task.md")
TASKS=["IDC","PRAD","PAAD","SKCM","COAD","READ","CCRCC","LUNG","LYMPH_IDC"]
NORM={"H-Optimus-0":"H-optimus-0"}
ORDER=["Phikon-v2","Midnight-12k","Virchow2","H-optimus-0","UNI2-h","Virchow","OpenMidnight"]

vals={}
for line in open(MD):
    if not line.startswith("| "): continue
    c=[x.strip() for x in line.strip().strip("|").split("|")]
    m=re.match(r"(.+) (base|tuned|delta)$",c[0])
    if not m or m.group(2)=="delta": continue
    bb=NORM.get(m.group(1),m.group(1))
    for t,cell in zip(TASKS,c[1:10]):
        v=float(cell.split("+/-")[0]) if "+/-" in cell else float(cell)
        vals[(bb,t,m.group(2))]=v
        if "+/-" in cell: vals[(bb,t,"sd")]=float(cell.split("+/-")[1])

# Prefer the raw per-seed values (same source as the retired seed_hest.tex) so the 3-decimal
# rounding is done once on the raw mean rather than twice via the md's 4 decimals.
try:
    import statistics
    import hest_ranks
    RAW = {"phikon2": "Phikon-v2", "midnight": "Midnight-12k", "virchow2": "Virchow2",
           "hoptimus0": "H-optimus-0", "uni2h": "UNI2-h", "virchow1": "Virchow",
           "openmidnightsq": "OpenMidnight"}
    for key, (base, _, n, per) in hest_ranks.our_values().items():
        bb = RAW[key]
        for i, t in enumerate(TASKS):
            seeds = [p[i] for p in per]
            vals[(bb, t, "base")] = base[i]
            vals[(bb, t, "tuned")] = statistics.mean(seeds)
            vals[(bb, t, "sd")] = statistics.stdev(seeds)
    print("values: raw per-seed via scripts/hest_ranks.py")
except Exception as e:  # noqa: BLE001
    print(f"values: {MD} (raw unavailable: {e})")

ranks,tail={},{}
import os
RANKS=str(PAPER_TABLES / "hest_ranks.tex") if os.path.exists(PAPER_TABLES / "hest_ranks.tex") else str(PAPER_TABLES / "unused/hest_ranks.tex")
for line in open(RANKS):
    if "$\\to$" not in line or line.startswith("%"): continue
    c=[x.strip() for x in line.rstrip(" \\\n").split("&")]
    bb=NORM.get(c[0],c[0])
    if bb not in ORDER or len(c) < 12: continue          # skip header / multicolumn rows
    tail[bb]=(c[10],c[11].rstrip("\\ "))
    for t,cell in zip(TASKS,c[1:10]):
        n=re.findall(r"\d+",re.sub(r"\\(gain|loss)","",cell))
        if len(n)>=2: ranks[(bb,t)]=(int(n[0]),int(n[1]))

def stack(top,bot):
    return "\\shortstack{"+top+" \\\\ {\\scriptsize "+bot+"}}"

out=["% Generated by scripts/make_hest_per_task.py -- do not hand-edit.",
     "\\begin{tabular}{l"+"c"*len(TASKS)+"cc}","\\toprule",
     " & \\multicolumn{9}{c}{per-task mean Pearson $r$\\,$\\uparrow$ $\\pm$ 2\\,SD (rank\\,$\\downarrow$), base $\\to$ fine-tuned} & & \\\\",
     "\\cmidrule(lr){2-10}",
     "Backbone & "+" & ".join(t.replace("_","\\_") for t in TASKS)
     +" & Mean $r$\\,$\\uparrow$ & $\\Sigma$rank\\,(position)\\,$\\downarrow$ \\\\","\\midrule"]
for bb in ORDER:
    cells=[]
    for t in TASKS:
        b=vals.get((bb,t,"base")); tu=vals.get((bb,t,"tuned")); r=ranks.get((bb,t))
        if b is None or tu is None: cells.append("--"); continue
        d=tu-b
        sd=vals.get((bb,t,"sd"))
        body=f"{tu:.3f}" + (f"$\\pm${2*sd:.3f}" if sd is not None else "")
        # Single paper-wide rule: \gain / \loss only when the change clears two
        # sample SDs (compared at the printed 3-dp precision, as elsewhere);
        # plain otherwise, and plain when there is no spread.  Pearson r is
        # higher-is-better.  The rank sub-line below keeps its own convention.
        if sd is not None and round(abs(d),3) > round(2*sd,3):
            body=f"\\gain{{{body}}}" if d>0 else f"\\loss{{{body}}}"
        top=f"{b:.3f}$\\to${body}"
        if r:
            rb,rt=r
            rtxt=f"{rt}"
            rtxt=f"\\gain{{{rtxt}}}" if rt<rb else (f"\\loss{{{rtxt}}}" if rt>rb else rtxt)
            cells.append(stack(top,f"({rb}$\\to${rtxt})"))
        else:
            cells.append(top)
    mean,rs=tail.get(bb,("--","--"))
    out.append(f"{bb} & "+" & ".join(cells)+f" & {mean} & {rs} \\\\")
    if bb != ORDER[-1]: out.append("\\addlinespace[2pt]")
out+=["\\bottomrule","\\end{tabular}"]
open(PAPER_TABLES / "hest_per_task.tex","w").write("\n".join(out)+"\n")
print(f"wrote {PAPER_TABLES}/hest_per_task.tex")
