#!/usr/bin/env python3
"""Merged HEST + CPTAC retention table for the main body.

Both halves are transcribed from tables already generated elsewhere -- the HEST columns
from tables/hest_per_task.tex (itself generated by make_hest_per_task.py) and the CPTAC
column from tables/cptac.tex -- so this file introduces no new measurement.  The HEST
per-task breakdown stays in the appendix; the body carries only the aggregate.
"""
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "scripts"))
from _config import PAPER_TABLES  # noqa: E402
ORDER = ["Phikon-v2", "Midnight-12k", "Virchow2", "H-optimus-0", "H-Optimus-0",
         "UNI2-h", "Virchow", "OpenMidnight"]


def rows_hest():
    out = {}
    for line in (PAPER_TABLES / "hest_per_task.tex").read_text().splitlines():
        if "&" not in line or line.lstrip().startswith(("\\", "%")):
            continue
        cols = [c.strip() for c in line.split("&")]
        name = cols[0]
        if len(cols) < 12:
            continue
        out[name] = (cols[-2], cols[-1].replace("\\\\", "").strip())
    return out


def rows_cptac():
    """{backbone: 'base$\\to$mark(tuned$\\pm$2SD)'} from tables/cptac.tex.

    tables/cptac.tex is a five-column table (Backbone, Base AUC, Fine-tuned AUC
    as $mean\\pm sd$, Delta, n).  This body table prints the same measurement as
    a single base -> fine-tuned cell, spread widened to two sample SDs, and
    highlighted by the paper-wide value-cell rule: \\gain / \\loss only when the
    change clears two sample SDs, plain otherwise.  AUC is higher-is-better.
    """
    out = {}
    for line in (PAPER_TABLES / "cptac.tex").read_text().splitlines():
        m = re.match(r"^(\S[^&]*?) & (.+?) \\\\$", line)
        if not m or "Backbone" in m.group(1):
            continue
        cols = [x.strip() for x in m.group(2).split("&")]
        if len(cols) < 2:
            out[m.group(1).strip()] = m.group(2).strip()
            continue
        base = float(cols[0])
        mt = re.match(r"^\$([0-9.]+)\\pm([0-9.]+)\$$", cols[1])
        if not mt:
            out[m.group(1).strip()] = m.group(2).strip()
            continue
        tuned, sd = float(mt.group(1)), float(mt.group(2))
        sd2 = 2 * sd
        body = f"{tuned:.4f}$\\pm${sd2:.4f}"
        d = tuned - base
        if round(abs(d), 4) > round(sd2, 4):
            body = f"\\gain{{{body}}}" if d > 0 else f"\\loss{{{body}}}"
        out[m.group(1).strip()] = f"{base:.4f}$\\to${body}"
    return out


def main():
    h, c = rows_hest(), rows_cptac()
    tex = ["% Generated by scripts/make_hest_cptac.py -- do not hand-edit.",
           "\\begin{tabular}{lccc}", "\\toprule",
           "Backbone & HEST mean $r$\\,$\\uparrow$ & HEST $\\Sigma$rank\\,(position)\\,$\\downarrow$ "
           "& CPTAC AUC\\,$\\uparrow$ \\\\", "\\midrule"]
    seen = set()
    for name in ORDER:
        if name not in h or name in seen:
            continue
        seen.add(name)
        key = next((k for k in c if k.lower() == name.lower()), None)
        tex.append(f"{name} & {h[name][0]} & {h[name][1]} & {c[key] if key else '--'} \\\\")
    tex += ["\\bottomrule", "\\end{tabular}"]
    out = PAPER_TABLES / "hest_cptac.tex"
    out.write_text("\n".join(tex) + "\n")
    print(f"wrote {out} ({len(seen)} rows)")


if __name__ == "__main__":
    main()
