#!/usr/bin/env python3
"""PathoROB submetrics, base vs tuned, per dataset -- the appendix table's proper form.

PathoROB's ``results_summary.json`` carries several scalars per dataset.  The ones that
matter for the paper, with their definitions from
PathoROB/pathorob/robustness_index/robustness_index_utils.py:

  balanced_accuracy       kNN classifier balanced accuracy at k_opt.  The actual
                          prediction metric.
  ID_performance          SS / (SS + OS): among same-centre neighbours, the fraction
                          that share the biological class.
  OOD_performance         SO / (SO + OO): among other-centre neighbours, the fraction
                          that share the biological class.
  prediction_performance  (SS + SO) / (SS + SO + OS + OO): neighbour class purity
                          pooled over centres.  NOT a classifier accuracy.  It shares
                          its neighbour counts with RI = SO / (SO + OS).
  confounder_insensitivity  odds, unbounded (see docs/ memory note).
  robustness_index        SO / (SO + OS).

Seeds enter at their OWN 1-SE-selected checkpoint (same rule as seed_stats.py), so the
tuned column is "at the selected checkpoint", never a fixed shared step.

    ./.venv/bin/python scripts/pathorob_submetrics.py
      -> docs/pathorob_submetrics.md, docs/pathorob_submetrics.tex
"""
import json, statistics, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import seed_stats as ss  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
OUT = Path("/data/ryan.kim/pathfm-full-evals/pathorob/results/robustness_index")
DATASETS = ["tcga", "camelyon", "tolkach_esca"]
DS_LABEL = {"tcga": "TCGA $2\\times2$", "camelyon": "Camelyon", "tolkach_esca": "Tolkach-ESCA"}
BACKBONES = ["phikon2", "midnight", "virchow2", "hoptimus0", "uni2h", "openmidnightsq", "virchow1", "virchow2f"]
BB_LABEL = {"phikon2": "Phikon-v2", "midnight": "Midnight-12k", "virchow2": "Virchow2",
            "hoptimus0": "H-optimus-0", "uni2h": "UNI2-h", "openmidnightsq": "OpenMidnight",
            "virchow1": "Virchow", "virchow2f": "Virchow2 (fp32 attack)"}
FIELDS = [("balanced_accuracy", "Bal. acc."), ("ID_performance", "ID purity"),
          ("OOD_performance", "OOD purity"), ("prediction_performance", "Pooled purity"),
          ("robustness_index", "RI")]


def summary(cell, ds):
    p = OUT / f"{cell}_clsmean" / ds / "-1_0/results_summary.json"
    return json.loads(p.read_text()) if p.exists() else None


def cells_for(bb):
    all_cells = sorted(d.name for d in ss.CELLS.iterdir() if (d / "model.py").exists())
    base = ss.BASE_CELL.get(bb, f"{bb}-base-control")
    seeds = [c for c in all_cells if c.startswith(f"{bb}-c50-s") and ss.rule_selected(c)
             and summary(c, "tcga") is not None]
    return base, seeds


def stat(vals):
    vals = [v for v in vals if v is not None]
    if not vals:
        return None, None, 0
    if len(vals) == 1:
        return vals[0], None, 1
    return statistics.mean(vals), statistics.stdev(vals), len(vals)


def main():
    md = ["# PathoROB submetrics, base vs tuned, per dataset", "",
          "**Generated file -- do not hand-edit.**  Regenerate with",
          "`./.venv/bin/python scripts/pathorob_submetrics.py`.", "",
          "Definitions (PathoROB `robustness_index_utils.py`): `balanced_accuracy` is the kNN",
          "classifier's balanced accuracy at `k_opt` -- the only true prediction metric here.",
          "`ID` = SS/(SS+OS), `OOD` = SO/(SO+OO), `pooled` = (SS+SO)/(SS+SO+OS+OO) are",
          "neighbour class-purity fractions built from the same neighbour counts as",
          "RI = SO/(SO+OS).  `pooled` is what PathoROB names `prediction_performance`; it is",
          "NOT a classifier accuracy.  Tuned = mean +/- SD over seeds at each seed's own",
          "1-SE-selected checkpoint (same rule as seed_stats.py).", ""]
    tex = ["% Generated by scripts/pathorob_submetrics.py -- do not hand-edit.",
           "\\begin{tabular}{llcccccc}", "\\toprule",
           "Backbone & Dataset & $n$ & Bal. acc. & ID purity & OOD purity & Pooled purity & RI \\\\",
           "\\midrule"]
    for bb in BACKBONES:
        base, seeds = cells_for(bb)
        if summary(base, "tcga") is None and not seeds:
            continue
        md += [f"## {bb}", "", f"base: {base}; seed cells: {', '.join(seeds) or 'none'}", "",
               "| dataset | n | " + " | ".join(f"{lab} base -> tuned" for _, lab in FIELDS) + " |",
               "|---|---|" + "---|" * len(FIELDS)]
        first = True
        for ds in DATASETS + ["mean"]:
            cells_md, cells_tex = [], []
            n_used = 0
            for key, lab in FIELDS:
                if ds == "mean":
                    def val(c):
                        vs = [summary(c, d) for d in DATASETS]
                        return None if any(v is None for v in vs) else sum(v[key] for v in vs) / 3
                else:
                    def val(c, ds=ds):
                        s = summary(c, ds)
                        return None if s is None else s[key]
                b = val(base)
                m, sd, n = stat([val(s) for s in seeds])
                n_used = max(n_used, n)
                bs = "--" if b is None else f"{b:.3f}"
                if m is None:
                    ts = "--"
                elif sd is None:
                    ts = f"{m:.3f}"
                else:
                    ts = f"{m:.3f} +/- {sd:.3f}"
                delta = "" if (b is None or m is None) else f" ({m - b:+.3f})"
                cells_md.append(f"{bs} -> {ts}{delta}")
                ttex = ts.replace("+/-", "$\\pm$")
                cells_tex.append(f"{bs}$\\to${ttex}")
            label = "mean of 3" if ds == "mean" else ds
            md.append(f"| {label} | {n_used} | " + " | ".join(cells_md) + " |")
            bbcol = BB_LABEL[bb] if first else ""
            first = False
            dsl = "Mean" if ds == "mean" else DS_LABEL[ds]
            tex.append(f"{bbcol} & {dsl} & {n_used} & " + " & ".join(cells_tex) + " \\\\")
        md.append("")
        tex.append("\\midrule")
    tex[-1] = "\\bottomrule"
    tex.append("\\end{tabular}")
    (REPO / "docs/pathorob_submetrics.md").write_text("\n".join(md))
    (REPO / "docs/pathorob_submetrics.tex").write_text("\n".join(tex) + "\n")
    print("wrote docs/pathorob_submetrics.md and .tex")


if __name__ == "__main__":
    main()
