#!/usr/bin/env python3
"""Raw per-seed values (base + each of the n adapter seeds), unaggregated.

Every other generated table (seed_stats.py, seed_spread_tables.py, hest_ranks.py,
cptac_table.py) reports base -> mean +/- SD.  This script exists for the cases where the
raw per-seed numbers themselves are wanted -- e.g. to hand-check an SD, or to re-aggregate
with a different pooling rule -- rather than the formatted cell.  It reuses the same loaders
and the same cell-selection rule (seed_stats.rule_selected / seed_stats.BASE_CELL) so it
cannot silently disagree with the tables that ARE published.

Deliberately NOT a LaTeX table and NOT written under waiv-asci/tables/: this is a
diagnostic dump, not a paper artifact. Default output is a scratch directory (JSON + a
human-readable text table).

Metrics (aggregate, one number per cell -- no per-task/per-dataset breakdown; that lives in
seed_spread_tables.py):
  pathorob_ri   PathoROB mean RI over 3 datasets              (seed_stats.ri_of)
  hest          HEST mean Pearson r over 9 tasks               (seed_stats.hest_of)
  cptac_auc     CPTAC (Patho-Bench subset) macro-OvR AUC       (cptac_table.cptac_of)
  thunder_knn   THUNDER k-NN macro-F1 aggregate row
  thunder_lp    THUNDER linear-probe macro-F1 aggregate row
  thunder_fewshot  THUNDER 16-shot macro-F1 aggregate row
  thunder_ece   THUNDER linear-probe ECE aggregate row

Usage:
    ./.venv/bin/python scripts/seed_raw_table.py [--out-dir DIR]

Writes <out-dir>/seed_raw.json and <out-dir>/seed_raw.txt. Default out-dir is
$SPECTRA_REPO/scratch_seed_raw (created if missing); pass --out-dir to redirect,
e.g. into a scratchpad.
"""
import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _config import REPO as _REPO  # noqa: E402
import seed_stats as S       # noqa: E402
import cptac_table as C      # noqa: E402

ORDER = ["phikon2", "midnight", "virchow2", "hoptimus0", "uni2h", "virchow1", "openmidnightsq"]
LABEL = {"phikon2": "Phikon-v2", "midnight": "Midnight-12k", "virchow2": "Virchow2",
         "hoptimus0": "H-optimus-0", "uni2h": "UNI2-h", "virchow1": "Virchow",
         "openmidnightsq": "OpenMidnight"}

# (metric key, display name, aggregate-row key into seed_stats.THUNDER_TASKS, or None,
#  decimals, is a THUNDER pct-point metric)
THUNDER_METRICS = [
    ("thunder_knn", "THUNDER k-NN", ("benchmark_knn", "knn", "f1", "")),
    ("thunder_lp", "THUNDER LP", ("benchmark_linear_probing", "linear_probing", "f1", "")),
    ("thunder_fewshot", "THUNDER few-shot", ("benchmark_simple_shot", "simple_shot", "f1", "16")),
    ("thunder_seg", "THUNDER segmentation", ("benchmark_segmentation", "segmentation", "f1", "")),
    ("thunder_ece", "THUNDER ECE", ("benchmark_calibration", "linear_probing", "ECE", "")),
]

# LaTeX table blocks, in the order requested: (metric key in `entry`, display name, decimals)
# CPTAC AUC and PathoROB RI / HEST r use 3 decimals; THUNDER rows are already scaled to
# percentage points, so 1 decimal.
TEX_BLOCKS = [
    ("pathorob_ri", "PathoROB mean RI", 3),
    ("hest", "HEST mean $r$", 3),
    ("cptac_auc", "CPTAC AUC", 3),
    ("thunder_knn", "THUNDER k-NN F1", 1),
    ("thunder_lp", "THUNDER LP F1", 1),
    ("thunder_fewshot", "THUNDER 16-shot F1", 1),
    ("thunder_seg", "THUNDER segmentation F1", 1),
    ("thunder_ece", "THUNDER LP ECE", 1),
]

_SEED_RE = re.compile(r"-s(\d+)-step(\d+)$")


def seed_id_step(cell):
    """(seed id, step) parsed from a cell name like '...-c50-s0-step200'."""
    m = _SEED_RE.search(cell)
    return (int(m.group(1)), int(m.group(2))) if m else (None, None)


def seeds_for(bb, cells):
    base = S.BASE_CELL.get(bb, f"{bb}-base-control")
    seeds = sorted((c for c in cells
                     if c.startswith(f"{bb}-c50-s") and c != base and S.rule_selected(c)),
                    key=lambda c: seed_id_step(c)[0])
    return base, seeds


def write_tex(result, path):
    """Metric x backbone x (base, seed1, seed2, seed3) LaTeX table.

    Columns are positional ('Seed 1/2/3' = increasing seed id per backbone), NOT the same
    physical seed across backbones -- some backbones skip a seed id (e.g. midnight uses
    s0/s1/s3, not s2). The actual seed ids and selected steps are printed to stdout by
    main() for the caption; they are deliberately not embedded in the table body.
    """
    lines = ["% Generated by scripts/seed_raw_table.py -- do not hand-edit.",
             "\\begin{tabular}{llcccc}", "\\toprule",
             "Metric & Backbone & Base & Seed a & Seed b & Seed c \\\\", "\\midrule"]
    for i, (key, name, nd) in enumerate(TEX_BLOCKS):
        if i > 0:
            lines.append("\\midrule")
        for j, bb in enumerate(ORDER):
            d = result[bb][key]
            b = "--" if d["base"] is None else f"{d['base']:.{nd}f}"
            svals = [("--" if v is None else f"{v:.{nd}f}") for v in d["seeds"]]
            svals += ["--"] * (3 - len(svals))          # pad to 3 columns if a seed is missing
            label = name if j == 0 else ""
            lines.append(f"{label} & {LABEL[bb]} & {b} & " + " & ".join(svals[:3]) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")



# Per-benchmark per-seed blocks, one file each, consumed as the bottom block of the
# appendix's single table per benchmark (waiv-asci/appendix.tex). Same values as the
# combined seed_raw.tex, regrouped by benchmark so the paper carries ONE table per
# benchmark instead of a separate raw-per-seed table.
PER_BENCHMARK = {
    # file stem: [(metric key, column-group label, decimals), ...]
    "pathorob": [("pathorob_ri", "Mean RI", 3)],
    "hest":     [("hest", "Mean $r$", 3)],
    "cptac":    [("cptac_auc", "Macro-OvR AUC", 3)],
    "thunder":  [("thunder_knn", "$k$-NN F1", 1), ("thunder_lp", "LP F1", 1),
                 ("thunder_fewshot", "16-shot F1", 1), ("thunder_seg", "Seg.\\ F1", 1),
                 ("thunder_ece", "LP ECE", 1)],
}


def write_per_benchmark_tex(result, out_dir):
    """One tabular per benchmark: rows = backbones, columns = (Base, Seed 1, 2, 3) per
    metric group. Seed columns are ordered by seed id within backbone, exactly as in
    write_tex; values are formatted with the same decimals, so every cell here is a
    verbatim copy of the corresponding seed_raw.tex cell."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    for stem, groups in PER_BENCHMARK.items():
        ncol = 1 + 4 * len(groups)
        lines = ["% Generated by scripts/seed_raw_table.py --tex-dir -- do not hand-edit.",
                 "\\begin{tabular}{l" + "cccc" * len(groups) + "}", "\\toprule"]
        if len(groups) > 1:
            head = " & ".join(f"\\multicolumn{{4}}{{c}}{{{lab}}}" for _, lab, _ in groups)
            lines.append(" & " + head + " \\\\")
            lines.append("".join(f"\\cmidrule(lr){{{2+4*i}-{5+4*i}}}" for i in range(len(groups))))
        lines.append("Backbone & " + " & ".join(["Base & Seed a & Seed b & Seed c"] * len(groups)) + " \\\\")
        lines.append("\\midrule")
        for bb in ORDER:
            cells = []
            for key, _, dec in groups:
                e = result[bb][key]
                fmt = lambda v: "--" if v is None else f"{v:.{dec}f}"
                svals = [fmt(v) for v in e["seeds"]] + ["--"] * (3 - len(e["seeds"]))
                cells += [fmt(e["base"])] + svals[:3]
            lines.append(f"{LABEL[bb]} & " + " & ".join(cells) + " \\\\")
        lines += ["\\bottomrule", "\\end{tabular}"]
        path = out_dir / f"perseed_{stem}.tex"
        path.write_text("\n".join(lines) + "\n")
        print(f"wrote {path} ({ncol} columns)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", default=str(_REPO / "scratch_seed_raw"))
    ap.add_argument("--tex", default=None, help="also write a LaTeX table to this path")
    ap.add_argument("--tex-dir", default=None,
                    help="also write per-benchmark per-seed tabulars perseed_{pathorob,hest,cptac,thunder}.tex into DIR")
    args = ap.parse_args()
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    cells = sorted(d.name for d in S.CELLS.iterdir() if d.is_dir() and (d / "model.py").exists())
    thunder_rows = S.load_thunder()

    result = {}
    txt = ["# Raw per-seed values (base + each seed's own 1-SE-selected checkpoint)", "",
           "Generated by scripts/seed_raw_table.py -- diagnostic dump, not a paper table.", ""]

    for bb in ORDER:
        base_cell, seeds = seeds_for(bb, cells)
        entry = {"base_cell": base_cell, "seed_cells": seeds,
                  "seed_id_step": [seed_id_step(s) for s in seeds]}

        rb = S.ri_of(base_cell)
        if rb is None:
            rb = S.base_from_verdict(bb, "RI")
        entry["pathorob_ri"] = {"base": rb, "seeds": [S.ri_of(s) for s in seeds]}

        hb = S.base_from_verdict(bb, "HEST")
        entry["hest"] = {"base": hb, "seeds": [S.hest_of(s) for s in seeds]}

        cb = C.cptac_of(base_cell)
        entry["cptac_auc"] = {"base": cb, "seeds": [C.cptac_of(s) for s in seeds]}

        for key, _name, k in THUNDER_METRICS:
            tb = thunder_rows.get(base_cell, {}).get(k)
            entry[key] = {"base": tb, "seeds": [thunder_rows.get(s, {}).get(k) for s in seeds]}

        result[bb] = entry

        txt.append(f"## {LABEL[bb]}  ({bb})")
        txt.append(f"base cell: {base_cell}    seed cells: {', '.join(seeds) or 'none'} (n={len(seeds)})")
        txt.append("")
        txt.append(f"{'metric':16s} {'base':>10s}   seeds")
        rows = [("PathoROB RI", entry["pathorob_ri"]),
                ("HEST r", entry["hest"]),
                ("CPTAC AUC", entry["cptac_auc"])] + \
               [(name, entry[key]) for key, name, _ in THUNDER_METRICS]
        for name, d in rows:
            b = "--" if d["base"] is None else f"{d['base']:.4f}"
            svals = ", ".join("--" if v is None else f"{v:.4f}" for v in d["seeds"])
            txt.append(f"{name:16s} {b:>10s}   {svals}")
        txt.append("")

    (out_dir / "seed_raw.json").write_text(json.dumps(result, indent=2) + "\n")
    (out_dir / "seed_raw.txt").write_text("\n".join(txt) + "\n")
    print(f"wrote {out_dir / 'seed_raw.json'}")
    print(f"wrote {out_dir / 'seed_raw.txt'}")

    missing_seg = [bb for bb in ORDER
                   if result[bb]["thunder_seg"]["base"] is None
                   and not any(v is not None for v in result[bb]["thunder_seg"]["seeds"])]
    if missing_seg:
        print(f"NOTE: THUNDER segmentation missing for: {', '.join(LABEL[b] for b in missing_seg)}")

    if args.tex_dir:
        write_per_benchmark_tex(result, args.tex_dir)

    if args.tex:
        tex_path = Path(args.tex)
        write_tex(result, tex_path)
        print(f"wrote {tex_path}")

    print("\nseed ids and selected steps, in the order used for Seed 1/2/3 columns:")
    for bb in ORDER:
        pairs = ", ".join(f"s{sid}@{step}" for sid, step in result[bb]["seed_id_step"])
        print(f"  {LABEL[bb]:14s} base={result[bb]['base_cell']}  seeds: {pairs or 'none'}")


if __name__ == "__main__":
    main()
