#!/usr/bin/env python3
"""Across-seed spread tables for the paper appendix.

Every fine-tuned number the paper reports is a mean over the shipped c50
recipe's adapter seeds (n=3), each at its own 1-SE-selected checkpoint
(scripts/seed_stats.py).  The aggregate tables already carry +/- 2 SD, but
the per-task HEST table and the per-dataset THUNDER figure do not.  This
script tabulates the per-task / per-dataset spread so every main-body
claim that is read against "seed spread" has a tabulated spread to be read
against.

Outputs (LaTeX, \\input from waiv-asci/appendix.tex):

  tables/seed_hest.tex            HEST per task, 9 tasks x 7 backbones
  tables/seed_thunder_knn.tex     THUNDER k-NN macro-F1 per dataset
  tables/seed_thunder_lp.tex      THUNDER linear-probe macro-F1 per dataset
  tables/seed_thunder_fewshot.tex THUNDER 16-shot macro-F1 per dataset
  tables/seed_thunder_seg.tex     THUNDER segmentation F1 per dataset
  tables/seed_thunder_ece.tex     THUNDER linear-probe ECE per dataset
  tables/seed_thunder_adv.tex     THUNDER adversarial F1 drop per dataset
                                  (fp32-attack cells, thunder_ranks.FP32_CELLS)

Cell format: base -> tuned +/- 2 SD, sample SD over the n seeds; the tuned
value is bold when |tuned - base| exceeds 2 SD.  The Mean row/column is the
mean over tasks/datasets; its SD is the SD across seeds of each seed's own
mean, so it matches the aggregate tables (thunder_ranks.py, hest_ranks.py).

Data sources are the same cells the paper tables use: hest_ranks.our_values()
for HEST and seed_stats.load_thunder() for THUNDER (same cell selection as
scripts/thunder_per_ds.py, which draws the figure).

    ./.venv-hest/bin/python scripts/seed_spread_tables.py
"""
import statistics
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _config import PAPER_TABLES  # noqa: E402
import hest_ranks  # noqa: E402
import seed_stats as S  # noqa: E402
import thunder_ranks as TR  # noqa: E402

OUT = PAPER_TABLES
HEADER = "% Generated by scripts/seed_spread_tables.py -- do not hand-edit.\n"

BB = ["phikon2", "midnight", "virchow2", "hoptimus0", "uni2h", "virchow1", "openmidnightsq"]
LABEL = {"phikon2": "Phikon-v2", "midnight": "Midnight-12k", "virchow2": "Virchow2",
         "hoptimus0": "H-optimus-0", "uni2h": "UNI2-h", "virchow1": "Virchow",
         "openmidnightsq": "OpenMidnight"}
DS_LABEL = {"patch_camelyon": "pcam", "tcga_crc_msi": "crc\\_msi", "tcga_tils": "tils",
            "tcga_uniform": "tcga\\_unif", "spider_breast": "spider\\_br",
            "spider_colorectal": "spider\\_col", "spider_skin": "spider\\_sk",
            "spider_thorax": "spider\\_th", "break_his": "breakhis",
            "segpath_epithelial": "segpath\\_epi", "segpath_lymphocytes": "segpath\\_lym"}

# (file stem, task, metric, setting, higher_is_better, adversarial)
PANELS = [
    ("knn", "knn", "f1", "", True, False),
    ("lp", "linear_probing", "f1", "", True, False),
    ("fewshot", "simple_shot", "f1", "16", True, False),
    ("seg", "segmentation", "f1", "", True, False),
    ("ece", "linear_probing", "ECE", "", False, False),
    ("adv", "adversarial_attack", "f1", "drop", False, True),
]


def cell(base, seeds, nd, n_expected=3):
    """base -> mean +/- 2 SD; bold tuned when the change clears 2 SD."""
    m = statistics.mean(seeds)
    sd2 = 2 * statistics.stdev(seeds) if len(seeds) > 1 else float("nan")
    t = f"{m:.{nd}f}$\\pm${sd2:.{nd}f}"
    # compare at the printed precision so bold never contradicts the digits shown
    if round(abs(m - base), nd) > round(sd2, nd):
        t = f"\\textbf{{{t}}}"
    if len(seeds) != n_expected:
        t += f"$^{{(n={len(seeds)})}}$"
    return f"{base:.{nd}f}$\\to${t}"


def tabular(row_labels, col_labels, body, corner):
    out = [HEADER + "\\begin{tabular}{l" + "c" * len(col_labels) + "}", "\\toprule",
           corner + " & " + " & ".join(col_labels) + " \\\\", "\\midrule"]
    for lab, cells in zip(row_labels, body):
        if lab == "Mean":
            out.append("\\midrule")
        out.append(lab + " & " + " & ".join(cells) + " \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out) + "\n"


def hest():
    res = hest_ranks.our_values()
    tasks = hest_ranks.TASKS
    body, summary = [], []
    for i, t in enumerate(tasks + ["Mean"]):
        row = []
        for bb in BB:
            base, _, n, per = res[bb]
            if t == "Mean":
                b = statistics.mean(base)
                s = [statistics.mean(p) for p in per]
            else:
                b = base[i]
                s = [p[i] for p in per]
            row.append(cell(b, s, 3))
            if t != "Mean":
                d = statistics.mean(s) - b
                summary.append((bb, t, d, 2 * statistics.stdev(s)))
        body.append(row)
    labels = [t.replace("_", "\\_") for t in tasks] + ["Mean"]
    (OUT / "seed_hest.tex").write_text(tabular(labels, [LABEL[b] for b in BB], body, "Task"))
    up = [x for x in summary if x[2] > 0]
    down = [x for x in summary if x[2] < 0]
    print(f"HEST per-task: {len(summary)} cells; {len(up)} up ({sum(abs(d) > s for _, _, d, s in up)} "
          f"beyond 2 SD), {len(down)} down ({sum(abs(d) > s for _, _, d, s in down)} beyond 2 SD)")
    for bb, t, d, s in sorted(down, key=lambda x: x[2]):
        print(f"   down {LABEL[bb]:13s} {t:10s} {d:+.4f} vs 2SD {s:.4f} {'RESOLVED' if abs(d) > s else 'within'}")


def thunder():
    rows = S.load_thunder()
    cells = sorted(d.name for d in S.CELLS.iterdir() if d.is_dir() and (d / "model.py").exists())
    for stem, task, metric, setting, hib, adv in PANELS:
        per_bb = {}
        datasets = set()
        for bb in BB:
            base = S.BASE_CELL.get(bb, f"{bb}-base-control")
            seeds = [c for c in cells if c.startswith(f"{bb}-c50-s") and c != base and S.rule_selected(c)]
            if adv:
                base, seeds = TR.FP32_CELLS.get(bb, (base, seeds))
            vals = {}
            for key, v in rows.get(base, {}).items():
                d, t, m, st = key
                if t != task or m != metric or st != setting or d.startswith("benchmark_"):
                    continue
                tuned = [rows.get(c, {}).get(key) for c in seeds]
                tuned = [x for x in tuned if x is not None]
                if tuned:
                    vals[d] = (v, tuned)
                    datasets.add(d)
            per_bb[bb] = vals
        datasets = sorted(datasets)
        body, resolved, total = [], 0, 0
        for d in datasets + ["Mean"]:
            row = []
            for bb in BB:
                vals = per_bb[bb]
                if d == "Mean":
                    ds_here = [x for x in datasets if x in vals]
                    b = statistics.mean(vals[x][0] for x in ds_here)
                    k = min(len(vals[x][1]) for x in ds_here)
                    s = [statistics.mean(vals[x][1][j] for x in ds_here) for j in range(k)]
                elif d in vals:
                    b, s = vals[d]
                else:
                    row.append("--")
                    continue
                row.append(cell(b, s, 1))
                if d != "Mean":
                    total += 1
                    resolved += abs(statistics.mean(s) - b) > 2 * statistics.stdev(s)
            body.append(row)
        labels = [DS_LABEL.get(d, d.replace("_", "\\_")) for d in datasets] + ["Mean"]
        (OUT / f"seed_thunder_{stem}.tex").write_text(
            tabular(labels, [LABEL[b] for b in BB], body, "Dataset"))
        print(f"THUNDER {stem:8s} {task}/{metric}/{setting or '-'}: {len(datasets)} datasets, "
              f"{resolved}/{total} cells beyond 2 SD")
        if stem in ("fewshot", "ece"):
            for bb in BB:
                for d, (b, s) in per_bb[bb].items():
                    m, sd2 = statistics.mean(s), 2 * statistics.stdev(s)
                    if (stem == "fewshot" and m < b) or (stem == "ece" and m > b):
                        print(f"   {stem} worse {LABEL[bb]:13s} {d:18s} {m - b:+.1f} vs 2SD {sd2:.1f} "
                              f"{'RESOLVED' if abs(m - b) > sd2 else 'within'}")


if __name__ == "__main__":
    hest()
    thunder()
